### PR TITLE
Update Bourbon, Neat and other dependencies

### PR DESCRIPTION
**Pull request by ericyan**
Bourbon was updated from 4.0.2 to 4.1.1 and Neat was updated from 1.6.0 to 1.7.1.
Some other dependencies were updated as well, mostly patch level changes.

This make sure Bourbon and Neat are up-to-date with current docs. Some functions like `modular-scale` will work as expected.

### CODE REVIEW

**Comment by joshuaogle** [comment]
@ericyan Looks great, thanks! I assume the Gemfile was changed too, but only the Gemfile.lock is in the commit. Could you add that?

**Comment by ericyan** [comment]
@joshuaogle Actually the `Gemfile` remains unchanged, as it does not contain any version specifiers. I just did a `bundle update` and everything will be updated to the latest version.

**Comment by joshuaogle** [comment]
@ericyan Ah, my mistake. If it's not going to be version locked, then the Gemfile.lock probably just shouldn't be in the repo. Any opinion on that?

Thanks for updating them for now though!

**Comment by ericyan** [comment]
@joshuaogle Given the fact that the Bourbon family depreciate functions and make backward incompatible changes quite actively, I think it is best to have a version-locked `Gemfile` after all.

This will make sure `bundle update` won't break anything, especially for legacy projects based on this repo: a legacy project built with Bourbon 4.0.2 may break if Bourbon being updated to 4.1.1.

On the other hand, for new projects, I do expect it start with the latest version of Bourbon. So we should update the `Gemfile` from time to time tracking upstream dependencies. May add a [Gemnasium](https://gemnasium.com/) badge?

**Pull request merged**
